### ISSUE TITLE
Custom.css file not copied during startup

### ISSUE THREAD

**Issue by BoruCz** [resoai/TileBoard-addon#12]
During startup I got this error:
 
[20:37:26] INFO: Symlink files to dist folder
rm: can't remove '/var/tileboard/styles/custom.css': No such file or directory
[cont-init.d] tile-board.sh: exited 1.

**Comment by Romkabouter** [comment]
https://github.com/resoai/TileBoard-addon/pull/11

**Comment by BoruCz** [comment]
Working well, thank you!
