### ISSUE TITLE
question about tile-board.sh (changing language)

### ISSUE THREAD

**Issue by Romkabouter** [resoai/TileBoard-addon#13]
Hi there,

In https://github.com/resoai/TileBoard-addon/blob/main/addon/rootfs/etc/cont-init.d/tile-board.sh is a loop:

```
for f in /config/$CONFIG_FOLDER/*;
do

```

This symlinks all files in the $CONFIG_FOLDER (default 'tileboard') to tileboard like this:
` ln -s /config/$CONFIG_FOLDER/$FILENAME /var/www/tileboard/$FILENAME`

Is there a reason for this? Because this does not work if you want a different locale.
The locale file should be in locales folder, but if you add a angular-locale_xx-xx.js files in it does not matter where you put it.
It always ends up in /var/www/tileboard/$FILENAME, but the locale file should be in /var/www/tileboard/**locales**/$FILENAME

Changing the language is therefore not possible in the add-on.

**Comment by rchl** [comment]
It's not very flexible right now. Should be improved. Personally, I'm not great with shell scripting. You can give it a go if you want. I would probably do it in python otherwise.

**Comment by Romkabouter** [comment]
ok cool, I'll see what I can do :)

**Comment by rchl** [comment]
This is now fixed. It will recursively symlink all files in the config folder.

The `custom.css` has an expectation so it can be either in the root of the config or in `styles/` and it will work either way.
