### ISSUE TITLE
History

### ISSUE THREAD

**Issue by alphasixtyfive** [resoai/TileBoard-addon#18]
Since CORS bug is not being fixed by anyone at HA, perhaps we could use `proxy_pass` in the add-on to fix history popups?

**Comment by rchl** [comment]
So you are thinking about exposing an endpoint like <ha_origin>/api-no-cors that would proxy the REST API but bypass CORS? That would be doable but not sure from the security endpoint if people would be happy about it?

Maybe if it's an opt-in option?

Personally, I don't think bypassing CORS given what CORS is about, but I wouldn't want to do it by default if that makes people uncomfortable.

On that note, I'm started working on Ingress support but that will of course will of course has no CORS issues as it runs from the same domain as HA.

**Comment by alphasixtyfive** [comment]
I think ingress will solve the problem!

**Comment by rchl** [comment]
Note that ingress loads inside the HA UI. Not sure if old tablets and things will like that.Also, it's heavier than just loading TB.
